<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('banks')->delete();

        \DB::table('banks')->insert(array (
            0 =>
            array (
                'id' => 1,
                'bridge_id' => 506,
            'name' => 'Crédit Coopératif Entreprise (Lecteur sans fil)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_cooperatif_particuliers.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            1 =>
            array (
                'id' => 2,
                'bridge_id' => 505,
                'name' => 'manager.one',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/manager-one.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            2 =>
            array (
                'id' => 3,
                'bridge_id' => 504,
                'name' => 'Ma French Bank',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/504_ma-french-bank.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            3 =>
            array (
                'id' => 4,
                'bridge_id' => 502,
                'name' => 'Epsor',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/502_epsor.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            4 =>
            array (
                'id' => 5,
                'bridge_id' => 499,
            'name' => 'Crédit Coopératif Entreprise (Mot de passe)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_cooperatif_particuliers.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            5 =>
            array (
                'id' => 6,
                'bridge_id' => 489,
                'name' => 'Pumpkin',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/pumpkin.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            6 =>
            array (
                'id' => 7,
                'bridge_id' => 488,
            'name' => 'PayPal (New)',
                'logo' => 'https://web.bankin.com/img/banks-logo/paypal.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            7 =>
            array (
                'id' => 8,
                'bridge_id' => 487,
                'name' => 'Anytime',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/anytime.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            8 =>
            array (
                'id' => 9,
                'bridge_id' => 486,
                'name' => 'Themis Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/themis.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            9 =>
            array (
                'id' => 10,
                'bridge_id' => 485,
                'name' => 'Banque Fiducial',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/fiducial.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'FIDCFR21',
                'process_time' => '24:00:00',
            ),
            10 =>
            array (
                'id' => 11,
                'bridge_id' => 481,
            'name' => 'Arkéa Banking Services (Compte courant et carte)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/481_arkea-banking-services.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            11 =>
            array (
                'id' => 12,
                'bridge_id' => 480,
            'name' => 'BPE Banque Privée (Compte courant et carte)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/480_bpe.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            12 =>
            array (
                'id' => 13,
                'bridge_id' => 478,
            'name' => 'Caisse d\'Epargne Entreprises (CENET Lecteur sans fil)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            13 =>
            array (
                'id' => 14,
                'bridge_id' => 476,
                'name' => 'CIC Banque Privée',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/07_CIC@2x.png',
                'primary_color' => '018289',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            14 =>
            array (
                'id' => 15,
                'bridge_id' => 475,
                'name' => 'Binck',
                'logo' => 'https://web.bankin.com/img/banks-logo/bink.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            15 =>
            array (
                'id' => 16,
                'bridge_id' => 474,
                'name' => 'Société de Banque Monaco',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/474_societe-banque-de-monaco.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            16 =>
            array (
                'id' => 17,
                'bridge_id' => 470,
                'name' => 'Banque Européenne du Crédit Mutuel',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            17 =>
            array (
                'id' => 18,
                'bridge_id' => 458,
            'name' => 'LCL Entreprise (Lecteur sans fil)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/03_lcl@2x.png',
                'primary_color' => '1F368B',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            18 =>
            array (
                'id' => 19,
                'bridge_id' => 452,
                'name' => 'Revolut Business FR',
                'logo' => 'https://web.bankin.com/img/banks-logo/neo/01Revolut%402x.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            19 =>
            array (
                'id' => 20,
                'bridge_id' => 451,
                'name' => 'Caisse d\'Epargne Nord France Europe',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            20 =>
            array (
                'id' => 21,
                'bridge_id' => 450,
                'name' => 'Caisse d\'Epargne Grand Est Europe',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            21 =>
            array (
                'id' => 22,
                'bridge_id' => 449,
                'name' => 'Caisse d\'Epargne Auvergne et Limousin',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            22 =>
            array (
                'id' => 23,
                'bridge_id' => 448,
                'name' => 'Caisse d\'Epargne Côte d\'Azur',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            23 =>
            array (
                'id' => 24,
                'bridge_id' => 447,
                'name' => 'Caisse d\'Epargne Loire-Centre',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            24 =>
            array (
                'id' => 25,
                'bridge_id' => 446,
                'name' => 'Caisse d\'Epargne Loire Drôme Ardèche',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            25 =>
            array (
                'id' => 26,
                'bridge_id' => 445,
                'name' => 'Caisse d\'Epargne Rhône Alpes',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            26 =>
            array (
                'id' => 27,
                'bridge_id' => 444,
                'name' => 'Caisse d\'Epargne Languedoc-Roussillon',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            27 =>
            array (
                'id' => 28,
                'bridge_id' => 443,
                'name' => 'Caisse d\'Epargne Aquitaine Poitou-Charentes',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            28 =>
            array (
                'id' => 29,
                'bridge_id' => 442,
                'name' => 'Caisse d\'Epargne Midi-Pyrénées',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            29 =>
            array (
                'id' => 30,
                'bridge_id' => 441,
                'name' => 'Caisse d\'Epargne Bretagne-Pays De Loire',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            30 =>
            array (
                'id' => 31,
                'bridge_id' => 440,
                'name' => 'Caisse d\'Epargne Bourgogne Franche-Comté',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            31 =>
            array (
                'id' => 32,
                'bridge_id' => 439,
                'name' => 'Caisse d\'Epargne Normandie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => 'CEPAFRPP142',
                'process_time' => '24:00:00',
            ),
            32 =>
            array (
                'id' => 33,
                'bridge_id' => 438,
                'name' => 'Caisse d\'Epargne Provence Alpes Corse',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            33 =>
            array (
                'id' => 34,
                'bridge_id' => 437,
                'name' => 'Caisse d\'Epargne Ile De France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => 'CEPAFRPP751',
                'process_time' => '24:00:00',
            ),
            34 =>
            array (
                'id' => 35,
                'bridge_id' => 436,
                'name' => 'Lydia',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/lydia.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            35 =>
            array (
                'id' => 36,
                'bridge_id' => 435,
                'name' => 'SwissLife',
                'logo' => 'https://web.bankin.com/img/banks-logo/swisslife.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            36 =>
            array (
                'id' => 37,
                'bridge_id' => 431,
            'name' => 'Swile (ex Lunchr)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/swile.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            37 =>
            array (
                'id' => 38,
                'bridge_id' => 428,
                'name' => 'Shine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/shine.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            38 =>
            array (
                'id' => 39,
                'bridge_id' => 425,
            'name' => 'Floa (ex Banque Casino)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/floa_bank.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            39 =>
            array (
                'id' => 40,
                'bridge_id' => 424,
                'name' => 'Banque Transatlantique',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_transatlantique.png',
                'primary_color' => '018289',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            40 =>
            array (
                'id' => 41,
                'bridge_id' => 423,
                'name' => 'C-Zam',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/czam.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            41 =>
            array (
                'id' => 42,
                'bridge_id' => 422,
                'name' => 'Revolut FR',
                'logo' => 'https://web.bankin.com/img/banks-logo/neo/01Revolut%402x.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            42 =>
            array (
                'id' => 43,
                'bridge_id' => 421,
                'name' => 'Qonto',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/qonto.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            43 =>
            array (
                'id' => 44,
                'bridge_id' => 420,
                'name' => 'Orange Bank',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/orange_bank.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'GPBAFRPP',
                'process_time' => '24:00:00',
            ),
            44 =>
            array (
                'id' => 45,
                'bridge_id' => 419,
                'name' => 'Yomoni',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/yomoni.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'YOMOFRP1',
                'process_time' => '24:00:00',
            ),
            45 =>
            array (
                'id' => 46,
                'bridge_id' => 418,
            'name' => 'Natixis Interépargne (Mail & N° d\'entreprise)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/natixis.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            46 =>
            array (
                'id' => 47,
                'bridge_id' => 417,
            'name' => 'Caisse d\'Epargne Entreprises (CENET)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            47 =>
            array (
                'id' => 48,
                'bridge_id' => 416,
                'name' => 'BNP Paribas Privée',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            48 =>
            array (
                'id' => 49,
                'bridge_id' => 415,
                'name' => 'Oney Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/oney.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            49 =>
            array (
                'id' => 50,
                'bridge_id' => 414,
                'name' => 'Carrefour Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/414_carrefour-banque.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'SOAPFR22',
                'process_time' => '24:00:00',
            ),
            50 =>
            array (
                'id' => 51,
                'bridge_id' => 413,
            'name' => 'N26 (Number 26)',
                'logo' => 'https://web.bankin.com/img/banks-logo/neo/04N26@2x.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            51 =>
            array (
                'id' => 52,
                'bridge_id' => 412,
                'name' => 'Unilend',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/unilend.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            52 =>
            array (
                'id' => 53,
                'bridge_id' => 411,
            'name' => 'Natixis Interépargne (N° d\'entreprise)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/natixis.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            53 =>
            array (
                'id' => 54,
                'bridge_id' => 410,
            'name' => 'Natixis Interépargne (E-mail)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/natixis.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            54 =>
            array (
                'id' => 55,
                'bridge_id' => 409,
                'name' => 'Compte Nickel',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/nickel.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            55 =>
            array (
                'id' => 56,
                'bridge_id' => 408,
                'name' => 'Simulator',
                'logo' => 'https://web.bankin.com/img/banks-logo/simulator.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            56 =>
            array (
                'id' => 57,
                'bridge_id' => 401,
                'name' => 'Banque BCP Particuliers',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_bcp.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            57 =>
            array (
                'id' => 58,
                'bridge_id' => 400,
                'name' => 'Banque Palatine Particuliers',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_palatine.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            58 =>
            array (
                'id' => 59,
                'bridge_id' => 388,
                'name' => 'Bq. Palatine - Entreprises & Prof. Immobilières',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/388_banque-palatine.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            59 =>
            array (
                'id' => 60,
                'bridge_id' => 350,
                'name' => 'BNP Guyane',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            60 =>
            array (
                'id' => 61,
                'bridge_id' => 349,
                'name' => 'BNP Martinique',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            61 =>
            array (
                'id' => 62,
                'bridge_id' => 348,
                'name' => 'BNP Guadeloupe',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            62 =>
            array (
                'id' => 63,
                'bridge_id' => 347,
                'name' => 'BNP Reunion',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            63 =>
            array (
                'id' => 64,
                'bridge_id' => 304,
                'name' => 'Oney - Banque Accord',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/oney_accord.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            64 =>
            array (
                'id' => 65,
                'bridge_id' => 303,
                'name' => 'BforBank',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/bforbank.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'BFBKFRP1',
                'process_time' => '24:00:00',
            ),
            65 =>
            array (
                'id' => 66,
                'bridge_id' => 302,
                'name' => 'Monabanq',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/monabanq.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            66 =>
            array (
                'id' => 67,
                'bridge_id' => 299,
            'name' => 'HSBC Professionnel (Elys PC)',
                'logo' => 'https://web.bankin.com/img/banks-logo/299_hsbc.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            67 =>
            array (
                'id' => 68,
                'bridge_id' => 298,
            'name' => 'HSBC Entreprise (Elys PC)',
                'logo' => 'https://web.bankin.com/img/banks-logo/299_hsbc.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            68 =>
            array (
                'id' => 69,
                'bridge_id' => 297,
                'name' => 'Banque De Savoie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_de_savoie.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            69 =>
            array (
                'id' => 70,
                'bridge_id' => 296,
                'name' => 'Banque SBE',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            70 =>
            array (
                'id' => 71,
                'bridge_id' => 295,
                'name' => 'HSBC Pro Question Mémorable',
                'logo' => 'https://web.bankin.com/img/banks-logo/299_hsbc.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            71 =>
            array (
                'id' => 72,
                'bridge_id' => 294,
                'name' => 'Banque Chalus',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_chalus.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            72 =>
            array (
                'id' => 73,
                'bridge_id' => 293,
            'name' => 'BNP Net Entreprises (Lecteur sans fil)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            73 =>
            array (
                'id' => 74,
                'bridge_id' => 292,
                'name' => 'Arkéa Banque Privée',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/arkea_banque_privee.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            74 =>
            array (
                'id' => 75,
                'bridge_id' => 289,
                'name' => 'Crédit Maritime Bretagne Normandie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_maritime.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            75 =>
            array (
                'id' => 76,
                'bridge_id' => 288,
                'name' => 'Crédit Maritime Atlantique',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_maritime.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            76 =>
            array (
                'id' => 77,
                'bridge_id' => 286,
                'name' => 'Crédit Maritime Littoral du Sud-Ouest',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_maritime.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            77 =>
            array (
                'id' => 78,
                'bridge_id' => 285,
                'name' => 'Groupama Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/groupama_banque.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            78 =>
            array (
                'id' => 79,
                'bridge_id' => 284,
                'name' => 'Crédit Coopératif Particuliers',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_cooperatif_particuliers.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            79 =>
            array (
                'id' => 80,
                'bridge_id' => 283,
            'name' => 'LCL Entreprise (Mot de passe)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/03_lcl@2x.png',
                'primary_color' => '1F368B',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            80 =>
            array (
                'id' => 81,
                'bridge_id' => 282,
                'name' => 'Société Générale Entreprises',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/09_Societe%20Generale@2x.png',
                'primary_color' => 'E9041E',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            81 =>
            array (
                'id' => 82,
                'bridge_id' => 281,
            'name' => 'BNP Net Entreprises (Navigation Sécurisée)',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            82 =>
            array (
                'id' => 83,
                'bridge_id' => 280,
            'name' => 'HSBC France (sans Secure Key)',
                'logo' => 'https://web.bankin.com/img/banks-logo/299_hsbc.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            83 =>
            array (
                'id' => 84,
                'bridge_id' => 279,
                'name' => 'AXA Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/axa_banque.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            84 =>
            array (
                'id' => 85,
                'bridge_id' => 179,
                'name' => 'LCL Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/03_lcl@2x.png',
                'primary_color' => '1F368B',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            85 =>
            array (
                'id' => 86,
                'bridge_id' => 172,
                'name' => 'BNP Paribas Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            86 =>
            array (
                'id' => 87,
                'bridge_id' => 167,
                'name' => 'Crédit Mutuel Massif Central Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            87 =>
            array (
                'id' => 88,
                'bridge_id' => 166,
                'name' => 'Crédit Mutuel de Bretagne Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/credit-mutuel-bretagne.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            88 =>
            array (
                'id' => 89,
                'bridge_id' => 165,
                'name' => 'Crédit Mutuel du Sud-Ouest Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/credit-mutuel-sud-ouest.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            89 =>
            array (
                'id' => 90,
                'bridge_id' => 156,
                'name' => 'Hello Bank',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/hello_bank.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            90 =>
            array (
                'id' => 91,
                'bridge_id' => 152,
                'name' => 'LCL Particuliers',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/03_lcl@2x.png',
                'primary_color' => '1F368B',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            91 =>
            array (
                'id' => 92,
                'bridge_id' => 151,
                'name' => 'La Banque Postale Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/la-banque-postale.png',
                'primary_color' => '17479E',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            92 =>
            array (
                'id' => 93,
                'bridge_id' => 147,
                'name' => 'Caisse d\'Epargne Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            93 =>
            array (
                'id' => 94,
                'bridge_id' => 145,
                'name' => 'Société Générale Pro',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/09_Societe%20Generale@2x.png',
                'primary_color' => 'E9041E',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            94 =>
            array (
                'id' => 95,
                'bridge_id' => 144,
                'name' => 'Milleis Banque',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/milleis.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            95 =>
            array (
                'id' => 96,
                'bridge_id' => 143,
                'name' => 'Crédit Mutuel Antilles-Guyane',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            96 =>
            array (
                'id' => 97,
                'bridge_id' => 142,
                'name' => 'Crédit Mutuel Massif Central',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            97 =>
            array (
                'id' => 98,
                'bridge_id' => 141,
                'name' => 'Crédit Mutuel Maine-Anjou',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            98 =>
            array (
                'id' => 99,
                'bridge_id' => 140,
                'name' => 'Crédit Mutuel Nord-Europe',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            99 =>
            array (
                'id' => 100,
                'bridge_id' => 139,
                'name' => 'Crédit Mutuel Océan',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            100 =>
            array (
                'id' => 101,
                'bridge_id' => 138,
                'name' => 'Crédit Mutuel du Sud-Ouest',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/credit-mutuel-sud-ouest.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            101 =>
            array (
                'id' => 102,
                'bridge_id' => 137,
                'name' => 'Banque Tarneaud',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_tarneaud.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'TARNFR2L',
                'process_time' => '24:00:00',
            ),
            102 =>
            array (
                'id' => 103,
                'bridge_id' => 136,
                'name' => 'Banque Rhône-Alpes',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_rhone_alpes.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            103 =>
            array (
                'id' => 104,
                'bridge_id' => 135,
                'name' => 'Banque Nuger',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_nuger.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'BNUGFR21',
                'process_time' => '24:00:00',
            ),
            104 =>
            array (
                'id' => 105,
                'bridge_id' => 134,
                'name' => 'Banque Laydernier',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_laydernier.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'LAYDFR2W',
                'process_time' => '24:00:00',
            ),
            105 =>
            array (
                'id' => 106,
                'bridge_id' => 133,
                'name' => 'Banque Courtois',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_courtois.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            106 =>
            array (
                'id' => 107,
                'bridge_id' => 132,
                'name' => 'Société Marseillaise de Crédit',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/societe_de_marseillaise_de_credit.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            107 =>
            array (
                'id' => 108,
                'bridge_id' => 131,
                'name' => 'Banque Kolb',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/banque_kolb.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            108 =>
            array (
                'id' => 109,
                'bridge_id' => 130,
                'name' => 'Crédit Mutuel de Bretagne',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/credit-mutuel-bretagne.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            109 =>
            array (
                'id' => 110,
                'bridge_id' => 129,
                'name' => 'ING France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/10_INGDirect@2x.png',
                'primary_color' => 'FF6600',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            110 =>
            array (
                'id' => 111,
                'bridge_id' => 128,
                'name' => 'Fortuneo',
                'logo' => 'https://web.bankin.com/img/banks-logo/128_fortuneo.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'FTNOFRP1',
                'process_time' => '24:00:00',
            ),
            111 =>
            array (
                'id' => 112,
                'bridge_id' => 126,
                'name' => 'American Express',
                'logo' => 'https://web.bankin.com/img/banks-logo/126_amex.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            112 =>
            array (
                'id' => 113,
                'bridge_id' => 122,
                'name' => 'Boursorama',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/08_Boursorama@2x.png',
                'primary_color' => 'D20073',
                'country' => 'FR',
                'bic' => 'BOUSFRPP',
                'process_time' => '24:00:00',
            ),
            113 =>
            array (
                'id' => 114,
                'bridge_id' => 120,
                'name' => 'Crédit Agricole Val de France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            114 =>
            array (
                'id' => 115,
                'bridge_id' => 119,
                'name' => 'Crédit Agricole Nord Est',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            115 =>
            array (
                'id' => 116,
                'bridge_id' => 118,
                'name' => 'Crédit Agricole Lorraine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            116 =>
            array (
                'id' => 117,
                'bridge_id' => 117,
                'name' => 'Crédit Agricole Franche Comté',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            117 =>
            array (
                'id' => 118,
                'bridge_id' => 116,
                'name' => 'Crédit Agricole Pyrénées Gascogne',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            118 =>
            array (
                'id' => 119,
                'bridge_id' => 115,
                'name' => 'Crédit Agricole Brie Picardie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            119 =>
            array (
                'id' => 120,
                'bridge_id' => 114,
                'name' => 'Crédit Agricole Alsace Vosges',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            120 =>
            array (
                'id' => 121,
                'bridge_id' => 113,
                'name' => 'Crédit Agricole Ile de France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            121 =>
            array (
                'id' => 122,
                'bridge_id' => 80,
                'name' => 'Crédit Agricole Touraine Poitou',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            122 =>
            array (
                'id' => 123,
                'bridge_id' => 79,
                'name' => 'Crédit Agricole Toulouse 31',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            123 =>
            array (
                'id' => 124,
                'bridge_id' => 78,
                'name' => 'Crédit Agricole Sud Rhône Alpes',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            124 =>
            array (
                'id' => 125,
                'bridge_id' => 77,
                'name' => 'Crédit Agricole Sud Méditerranée',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            125 =>
            array (
                'id' => 126,
                'bridge_id' => 76,
                'name' => 'Crédit Agricole Réunion',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            126 =>
            array (
                'id' => 127,
                'bridge_id' => 75,
                'name' => 'Crédit Agricole Provence Côte d\'Azur',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            127 =>
            array (
                'id' => 128,
                'bridge_id' => 74,
                'name' => 'Crédit Agricole Normandie Seine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            128 =>
            array (
                'id' => 129,
                'bridge_id' => 73,
                'name' => 'Crédit Agricole Normandie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            129 =>
            array (
                'id' => 130,
                'bridge_id' => 72,
                'name' => 'Crédit Agricole Nord Midi-Pyrénées',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            130 =>
            array (
                'id' => 131,
                'bridge_id' => 71,
                'name' => 'Crédit Agricole Nord De France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            131 =>
            array (
                'id' => 132,
                'bridge_id' => 70,
                'name' => 'Crédit Agricole Morbihan',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            132 =>
            array (
                'id' => 133,
                'bridge_id' => 69,
                'name' => 'Crédit Agricole Deux-Sèvres',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            133 =>
            array (
                'id' => 134,
                'bridge_id' => 66,
                'name' => 'Crédit Agricole Martinique-Guyane',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            134 =>
            array (
                'id' => 135,
                'bridge_id' => 65,
                'name' => 'Crédit Agricole Loire Haute Loire',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            135 =>
            array (
                'id' => 136,
                'bridge_id' => 64,
                'name' => 'Crédit Agricole Languedoc',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            136 =>
            array (
                'id' => 137,
                'bridge_id' => 63,
                'name' => 'Crédit Agricole Ille-et-Vilaine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            137 =>
            array (
                'id' => 138,
                'bridge_id' => 62,
                'name' => 'Crédit Agricole Guadeloupe',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            138 =>
            array (
                'id' => 139,
                'bridge_id' => 61,
                'name' => 'Crédit Agricole Finistère',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            139 =>
            array (
                'id' => 140,
                'bridge_id' => 60,
                'name' => 'Crédit Agricole Côtes d\'Armor',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            140 =>
            array (
                'id' => 141,
                'bridge_id' => 59,
                'name' => 'Crédit Agricole Corse',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            141 =>
            array (
                'id' => 142,
                'bridge_id' => 58,
                'name' => 'Crédit Agricole Charente Perigord',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            142 =>
            array (
                'id' => 143,
                'bridge_id' => 57,
                'name' => 'Crédit Agricole Charente-Maritime',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            143 =>
            array (
                'id' => 144,
                'bridge_id' => 56,
                'name' => 'Crédit Agricole Champagne-Bourgogne',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            144 =>
            array (
                'id' => 145,
                'bridge_id' => 55,
                'name' => 'Crédit Agricole Centre-Ouest',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            145 =>
            array (
                'id' => 146,
                'bridge_id' => 54,
                'name' => 'Crédit Agricole Centre France',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            146 =>
            array (
                'id' => 147,
                'bridge_id' => 53,
                'name' => 'Crédit Agricole Centre-Est',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            147 =>
            array (
                'id' => 148,
                'bridge_id' => 52,
                'name' => 'Crédit Agricole Atlantique Vendée',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            148 =>
            array (
                'id' => 149,
                'bridge_id' => 51,
                'name' => 'Crédit Agricole Anjou Maine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            149 =>
            array (
                'id' => 150,
                'bridge_id' => 50,
                'name' => 'Crédit Agricole Alpes Provence',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            150 =>
            array (
                'id' => 151,
                'bridge_id' => 49,
                'name' => 'Crédit Agricole Centre Loire',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            151 =>
            array (
                'id' => 152,
                'bridge_id' => 48,
                'name' => 'Crédit Agricole Aquitaine',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            152 =>
            array (
                'id' => 153,
                'bridge_id' => 40,
                'name' => 'Banque Populaire Du Sud',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPPPG',
                'process_time' => '24:00:00',
            ),
            153 =>
            array (
                'id' => 154,
                'bridge_id' => 39,
                'name' => 'Banque Populaire Méditerranée',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            154 =>
            array (
                'id' => 155,
                'bridge_id' => 38,
                'name' => 'Banque Populaire Grand Ouest',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            155 =>
            array (
                'id' => 156,
                'bridge_id' => 37,
                'name' => 'Banque Populaire Du Nord',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPLIL',
                'process_time' => '24:00:00',
            ),
            156 =>
            array (
                'id' => 157,
                'bridge_id' => 36,
                'name' => 'Banque Populaire Alsace Lorraine Champagne',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPMTZ',
                'process_time' => '24:00:00',
            ),
            157 =>
            array (
                'id' => 158,
                'bridge_id' => 35,
                'name' => 'Banque Populaire Du Massif Central',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            158 =>
            array (
                'id' => 159,
                'bridge_id' => 34,
                'name' => 'Banque Populaire Loire et Lyonnais',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            159 =>
            array (
                'id' => 160,
                'bridge_id' => 32,
                'name' => 'Banque Populaire Bourgogne Franche-Comté',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            160 =>
            array (
                'id' => 161,
                'bridge_id' => 31,
                'name' => 'Banque Populaire Atlantique',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPNAN',
                'process_time' => '24:00:00',
            ),
            161 =>
            array (
                'id' => 162,
                'bridge_id' => 30,
                'name' => 'Banque Populaire Aquitaine Centre Atlantique',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPBDX',
                'process_time' => '24:00:00',
            ),
            162 =>
            array (
                'id' => 163,
                'bridge_id' => 28,
                'name' => 'Banque Populaire Auvergne Rhône Alpes',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            163 =>
            array (
                'id' => 164,
                'bridge_id' => 25,
                'name' => 'Banque Populaire Occitane',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPTLS',
                'process_time' => '24:00:00',
            ),
            164 =>
            array (
                'id' => 165,
                'bridge_id' => 23,
                'name' => 'Bred',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/bred.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            165 =>
            array (
                'id' => 166,
                'bridge_id' => 21,
                'name' => 'Crédit Agricole Savoie',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/01_CA@2x.png',
                'primary_color' => '006147',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            166 =>
            array (
                'id' => 167,
                'bridge_id' => 20,
                'name' => 'Crédit du Nord',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/credit_du_nord.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            167 =>
            array (
                'id' => 168,
                'bridge_id' => 18,
                'name' => 'Banque Populaire Rives de Paris',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => 'CCBPFRPPMTG',
                'process_time' => '24:00:00',
            ),
            168 =>
            array (
                'id' => 169,
                'bridge_id' => 17,
                'name' => 'La Banque Postale Particulier',
                'logo' => 'https://web.bankin.com/img/banks-logo/fr/la-banque-postale.png',
                'primary_color' => '17479E',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            169 =>
            array (
                'id' => 170,
                'bridge_id' => 16,
                'name' => 'Crédit Mutuel - Site National',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/06_Credit%20Mutuel@2x.png',
                'primary_color' => 'E50006',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            170 =>
            array (
                'id' => 171,
                'bridge_id' => 15,
                'name' => 'Banque Populaire Val de France ',
                'logo' => 'https://web.bankin.com/img/banks-logo/40_banque_populaire.png',
                'primary_color' => '',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            171 =>
            array (
                'id' => 172,
                'bridge_id' => 14,
                'name' => 'CIC',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/07_CIC@2x.png',
                'primary_color' => '018289',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            172 =>
            array (
                'id' => 173,
                'bridge_id' => 6,
                'name' => 'BNP Paribas Particulier',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/12_BNPParisbasParticulier@2x.png',
                'primary_color' => '007942',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            173 =>
            array (
                'id' => 174,
                'bridge_id' => 5,
                'name' => 'Société Générale Particulier',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/09_Societe%20Generale@2x.png',
                'primary_color' => 'E9041E',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            174 =>
            array (
                'id' => 175,
                'bridge_id' => 4,
                'name' => 'Caisse d\'Epargne Particulier',
                'logo' => 'https://web.bankin.com/img/banks-logo/france/04_CaisseEpargne@2x.png',
                'primary_color' => 'DB0029',
                'country' => 'FR',
                'bic' => '',
                'process_time' => '24:00:00',
            ),
            175 =>
                array (
                    'id' => 176,
                    'bridge_id' => 0,
                    'name' => 'FINBANK ',
                    'logo' => config('app.url').'/storage/logo/logo_carre.png',
                    'primary_color' => 'DB0029',
                    'country' => 'FR',
                    'bic' => 'FINFRPPXXX',
                    'process_time' => '02:00:00',
                ),
        ));


    }
}
